//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.07 at 09:28:43 AM CET 
//


package name.saak.empire.schema;


import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the name.saak.empirebuilder.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Clear_QNAME = new QName("", "clear");
    private final static QName _Mountain_QNAME = new QName("", "mountain");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _SmallCityLoad_QNAME = new QName("", "load");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: name.saak.empirebuilder.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlRowMilepost }
     * 
     */
    public XmlRowMilepost createRowMilepost() {
        return new XmlRowMilepost();
    }

    /**
     * Create an instance of {@link XmlLoads }
     * 
     */
    public XmlLoads createLoads() {
        return new XmlLoads();
    }

    /**
     * Create an instance of {@link XmlLoad }
     * 
     */
    public XmlLoad createLoad() {
        return new XmlLoad();
    }

    /**
     * Create an instance of {@link XmlCities }
     * 
     */
    public XmlCities createCities() {
        return new XmlCities();
    }

    /**
     * Create an instance of {@link XmlSmallCity }
     * 
     */
    public XmlSmallCity createSmallCity() {
        return new XmlSmallCity();
    }

    /**
     * Create an instance of {@link XmlMediumCity }
     * 
     */
    public XmlMediumCity createMediumCity() {
        return new XmlMediumCity();
    }

    /**
     * Create an instance of {@link XmlMajorCity }
     * 
     */
    public XmlMajorCity createMajorCity() {
        return new XmlMajorCity();
    }

    /**
     * Create an instance of {@link XmlMap }
     * 
     */
    public XmlMap createMap() {
        return new XmlMap();
    }

    /**
     * Create an instance of {@link XmlRow }
     * 
     */
    public XmlRow createRow() {
        return new XmlRow();
    }

    /**
     * Create an instance of {@link XmlGame }
     * 
     */
    public XmlGame createGame() {
        return new XmlGame();
    }

    /**
     * Create an instance of {@link XmlCards }
     * 
     */
    public XmlCards createCards() {
        return new XmlCards();
    }

    /**
     * Create an instance of {@link XmlDemandCard }
     * 
     */
    public XmlDemandCard createDemandCard() {
        return new XmlDemandCard();
    }

    /**
     * Create an instance of {@link XmlDemand }
     * 
     */
    public XmlDemand createDemand() {
        return new XmlDemand();
    }

    /**
     * Create an instance of {@link XmlCity }
     * 
     */
    public XmlCity createCity() {
        return new XmlCity();
    }

    /**
     * Create an instance of {@link XmlMilepost }
     * 
     */
    public XmlMilepost createMilepost() {
        return new XmlMilepost();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRowMilepost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clear")
    public JAXBElement<XmlRowMilepost> createClear(XmlRowMilepost value) {
        return new JAXBElement<XmlRowMilepost>(_Clear_QNAME, XmlRowMilepost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRowMilepost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mountain")
    public JAXBElement<XmlRowMilepost> createMountain(XmlRowMilepost value) {
        return new JAXBElement<XmlRowMilepost>(_Mountain_QNAME, XmlRowMilepost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "load", scope = XmlSmallCity.class)
    @XmlIDREF
    public JAXBElement<Object> createSmallCityLoad(Object value) {
        return new JAXBElement<Object>(_SmallCityLoad_QNAME, Object.class, XmlSmallCity.class, value);
    }

}
