//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.07 at 09:28:43 AM CET 
//


package name.saak.empire.schema;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;choice>
 *           &lt;element name="small-city" type="{}small-city"/>
 *           &lt;element name="medium-city" type="{}medium-city"/>
 *           &lt;element name="major-city" type="{}major-city"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smallCityOrMediumCityOrMajorCity"
})
@XmlRootElement(name = "cities")
public class XmlCities {

    @XmlElements({
        @XmlElement(name = "small-city"),
        @XmlElement(name = "medium-city", type = XmlMediumCity.class),
        @XmlElement(name = "major-city", type = XmlMajorCity.class)
    })
    protected List<XmlSmallCity> smallCityOrMediumCityOrMajorCity;

    /**
     * Gets the value of the smallCityOrMediumCityOrMajorCity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smallCityOrMediumCityOrMajorCity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmallCityOrMediumCityOrMajorCity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlSmallCity }
     * {@link XmlMediumCity }
     * {@link XmlMajorCity }
     * 
     * 
     */
    public List<XmlSmallCity> getSmallCityOrMediumCityOrMajorCity() {
        if (smallCityOrMediumCityOrMajorCity == null) {
            smallCityOrMediumCityOrMajorCity = new ArrayList<XmlSmallCity>();
        }
        return this.smallCityOrMediumCityOrMajorCity;
    }

}
