//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.07 at 09:28:43 AM CET 
//


package name.saak.empire.schema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for milepost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="milepost">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="position-x" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="position-y" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "milepost")
@XmlSeeAlso({
    XmlSmallCity.class
})
public class XmlMilepost {

    @XmlAttribute(name = "position-x", required = true)
    protected int positionX;
    @XmlAttribute(name = "position-y", required = true)
    protected int positionY;

    /**
     * Gets the value of the positionX property.
     * 
     */
    public int getPositionX() {
        return positionX;
    }

    /**
     * Sets the value of the positionX property.
     * 
     */
    public void setPositionX(int value) {
        this.positionX = value;
    }

    /**
     * Gets the value of the positionY property.
     * 
     */
    public int getPositionY() {
        return positionY;
    }

    /**
     * Sets the value of the positionY property.
     * 
     */
    public void setPositionY(int value) {
        this.positionY = value;
    }

}
