name: verify on push

on:
  push:
    branches:
      - main
#on:
#  workflow_call:
#    inputs:
#      username:
#        description: 'A username passed from the caller workflow'
#        default: 'ingraban'
#        required: false
#        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.dmg staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging